### ISSUE TITLE
Set Object Property tuple vanishing

### ISSUE THREAD

**Issue by R3Ked** [retro-dev-rblx/Docs#30]
I'm making a game where you run from a deadly wall, and that's going to involve me cloning the wall. However, when I use Set Object Property to move the wall, unselect the block, then reselect the block, the values I set vanish. I assume they're still there, as when you add a new one it doesn't start at value 1, but you can't see them.

https://github.com/retro-dev-rblx/Docs/assets/20342336/b8419e98-31ce-4199-ab28-bc6aa4d97b1a

**Comment by FloofyPlasma** [comment]
This isn’t the place to make bug reports.
