### ISSUE TITLE
Bad dark mode color choice

### ISSUE THREAD

**Issue by quadsYT** [retro-dev-rblx/Docs#8]
on mac for the search bar in the top right on dark mode its purple text on a dark background causing it to be harder to read. 
![Screenshot 2023-07-01 at 16 01 29](https://github.com/retro-dev-rblx/Docs/assets/77026708/72804656-9aaa-43ab-9ccb-4df2a36ecf5e)

**Comment by FloofyPlasma** [comment]
Thanks for your report, the color has been made brighter. Refresh the page a few times if you don't see the changes.
